# Generated by Django 5.2.5 on 2025-12-27 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField(db_index=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'menu_food_rating',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='accounts.companyfloor')),
            ],
            options={
                'db_table': 'menu_daily_menu',
            },
        ),
        migrations.CreateModel(
            name='FloorFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_level_price_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('name_override', models.CharField(blank=True, max_length=255, null=True)),
                ('description_override', models.TextField(blank=True, null=True)),
                ('default_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_foods', to='accounts.companyfloor')),
            ],
            options={
                'db_table': 'menu_floor_food',
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('remaining_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('special_price_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('special_name_override', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='menu.dailymenu')),
                ('floor_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_items', to='menu.floorfood')),
            ],
            options={
                'db_table': 'menu_daily_menu_item',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('evening_snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=50)),
                ('category', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg')], max_length=50)),
                ('base_price_cents', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_foods', to='accounts.vendor')),
            ],
            options={
                'db_table': 'menu_food_item',
            },
        ),
        migrations.CreateModel(
            name='SpecialFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_foods', to='accounts.companyfloor')),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_foods', to='accounts.vendorbranch')),
            ],
            options={
                'db_table': 'menu_special_food',
            },
        ),
        migrations.CreateModel(
            name='VendorBranchFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_level_price_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_activations', to='menu.fooditem')),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foods', to='accounts.vendorbranch')),
            ],
            options={
                'db_table': 'menu_vendor_branch_food',
            },
        ),
        migrations.AddField(
            model_name='floorfood',
            name='vendor_branch_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_maps', to='menu.vendorbranchfood'),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['floor', 'week_day'], name='menu_daily__floor_i_18e0dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('floor', 'week_day')},
        ),
        migrations.AddIndex(
            model_name='dailymenuitem',
            index=models.Index(fields=['daily_menu', 'floor_food'], name='menu_daily__daily_m_2d6a4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenuitem',
            unique_together={('daily_menu', 'floor_food')},
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['vendor', 'name'], name='menu_food_i_vendor__249bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddIndex(
            model_name='specialfood',
            index=models.Index(fields=['vendor_branch', 'floor', 'available_from'], name='menu_specia_vendor__f6c95a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbranchfood',
            index=models.Index(fields=['vendor_branch', 'food'], name='menu_vendor_vendor__cc860c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbranchfood',
            unique_together={('vendor_branch', 'food')},
        ),
        migrations.AddIndex(
            model_name='floorfood',
            index=models.Index(fields=['floor', 'vendor_branch_food'], name='menu_floor__floor_i_e08508_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floorfood',
            unique_together={('floor', 'vendor_branch_food')},
        ),
    ]
