# Generated by Django 6.0.1 on 2026-01-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='foodrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='foodrating',
            name='order_item_id',
        ),
        migrations.RemoveField(
            model_name='foodrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='foodrating',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodrating',
            name='food',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='menu.vendorbranchfood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrating',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='foodrating',
            table=None,
        ),
    ]
