# Generated by Django 5.2.5 on 2025-12-27 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Disabled', 'Disabled')], default='Pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companybranch')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companybuilding')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendorservice_requested', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendorservice_responded', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendorbranch')),
            ],
            options={
                'db_table': 'service_vendor_service',
                'indexes': [models.Index(fields=['company', 'vendor'], name='service_ven_company_633315_idx'), models.Index(fields=['vendor', 'vendor_branch'], name='service_ven_vendor__ae1aa7_idx')],
            },
        ),
    ]
