# Generated by Django 5.2.5 on 2025-12-27 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWallet',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.employee')),
                ('daily_limit_cents', models.IntegerField(default=0)),
                ('monthly_limit_cents', models.IntegerField(default=0)),
                ('daily_used_cents', models.IntegerField(default=0)),
                ('monthly_used_cents', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wallet_employee_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('amount_cents', models.IntegerField()),
                ('type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('source', models.CharField(choices=[('Order', 'Order'), ('CompanyAdjustment', 'CompanyAdjustment'), ('Refund', 'Refund')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
    ]
