# Generated by Django 5.2.5 on 2025-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertype_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_otp',
            },
        ),
        migrations.AddField(
            model_name='companybranch',
            name='country',
            field=models.CharField(default='IN', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorbranch',
            name='country',
            field=models.CharField(default='IN', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorbranch',
            name='state',
            field=models.CharField(default='Haryana', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_b922ad_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='company_domain_1ab7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='companybranch',
            index=models.Index(fields=['company'], name='company_bra_company_1653ac_idx'),
        ),
        migrations.AddIndex(
            model_name='companybranch',
            index=models.Index(fields=['city'], name='company_bra_city_8784db_idx'),
        ),
        migrations.AddIndex(
            model_name='companybranch',
            index=models.Index(fields=['state'], name='company_bra_state_eba2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='companybuilding',
            index=models.Index(fields=['branch'], name='company_bui_branch__6527dc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='employee_full_na_b33199_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employee_employe_3e3e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='employee_company_61ef14_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='app_user_email_4a499e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='vendor_name_3e8102_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbranch',
            index=models.Index(fields=['vendor'], name='vendor_bran_vendor__1d2d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbranch',
            index=models.Index(fields=['city'], name='vendor_bran_city_a3fa22_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbranch',
            index=models.Index(fields=['state'], name='vendor_bran_state_896b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email'], name='email_otp_email_a21bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['is_used'], name='email_otp_is_used_5f2d68_idx'),
        ),
    ]
